apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-boot-react-example-configs
data:
  application.properties: |
    application.env=prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-react-example-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-react-example
  template:
    metadata:
      labels:
        app: spring-boot-react-example
    spec:
      containers:
      - name: spring-boot-react-example
        image: registry.gitlab.com/goenka811/spring-boot-react-example
        args: ["--spring.config.location=/etc/spring-boot-react-example/application.properties"]
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-vol
          mountPath: /etc/spring-boot-react-example
        readinessProbe:
          httpGet:
            path: /
            port: 8080
      volumes:
      - name: config-vol
        configMap:
          name: spring-boot-react-example-configs
      imagePullSecrets:
      - name: gitlab-auth
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-react-example-service
spec:
  type: LoadBalancer
  selector:
    app: spring-boot-react-example
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080

